---
settings:
  name: BlueXP ransomware protection
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents de protection contre les ransomwares BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez la protection contre les ransomwares BlueXP
      url: "/concept-ransomware-protection.html"
    - title: Prérequis
      url: "/rp-start-prerequisites.html"
    - title: Démarrage rapide
      url: "/rp-start-quick-start.html"
    - title: Configurez la protection BlueXP contre les ransomware
      url: "/rp-start-setup.html"
    - title: Accédez à la protection BlueXP contre les ransomware
      url: "/rp-start-login.html"
    - title: Configuration des licences
      url: "/rp-start-licenses.html"
    - title: Découvrir les workloads
      url: "/rp-start-discover.html"
    - title: Configurez les destinations de sauvegarde et activez la détection des
        menaces
      url: "/rp-use-settings.html"
    - title: FAQ
      url: "/rp-start-faq.html"
  - title: Utilisez la protection BlueXP contre les ransomwares
    entries:
    - title: Utilisez la présentation de la protection BlueXP contre les ransomwares
      url: "/rp-use-overview.html"
    - title: Consultez l'état des charges de travail à l'aide du tableau de bord
      url: "/rp-use-dashboard.html"
    - title: Protégez les workloads
      url: "/rp-use-protect.html"
    - title: Répondre à une alerte détectée
      url: "/rp-use-alert.html"
    - title: Évitez les attaques par ransomware
      url: "/rp-use-recover.html"
    - title: Télécharger des rapports
      url: "/rp-use-reports.html"
  - section: support
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
