---
sidebar: sidebar 
permalink: rp-reference-roles.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: 'La protection contre les ransomwares BlueXP  utilise le contrôle d"accès basé sur des rôles (RBAC) pour régir l"accès dont chaque utilisateur dispose à des fonctionnalités et des actions spécifiques. Le service utilise des rôles spécifiques à la protection contre les ransomware BlueXP  (RPS).' 
---
= La protection BlueXP  contre les ransomwares permet un accès basé sur des rôles aux fonctionnalités
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La protection contre les ransomwares BlueXP  emploie des rôles pour régir l'accès dont chaque utilisateur dispose pour des fonctionnalités et des actions spécifiques.

Le service utilise les rôles suivants propres à la protection contre les ransomwares BlueXP .

* *Protection anti-ransomware admin* : gestion des actions dans les onglets protéger, alertes, récupérer, Paramètres et Rapports.
* *Visualiseur de protection contre les ransomware* : afficher les données de charge de travail, afficher les données d'alerte, télécharger les données de récupération et télécharger les rapports.


La plateforme BlueXP  pour tous les services BlueXP  utilise les types de rôles suivants :

* *Les rôles de plate-forme* vous permettent de gérer des utilisateurs, de les affecter à des ressources et de leur donner des rôles ainsi que d'autres actions à l'échelle de la plate-forme.
+

TIP: Pour la découverte de la protection contre les ransomware BlueXP , vous devez avoir le rôle *Administrateur de l'organisation* en plus du rôle *Administrateur de la protection contre les ransomware*.

* *Les rôles des services de données* sont limités à un seul service de données spécifique. Vous pouvez avoir plusieurs rôles de services de données en fonction de votre travail. La protection contre les ransomwares BlueXP  est l'un des services de données BlueXP .


Pour plus de détails sur les rôles de plate-forme, voir https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Documentation d'installation et d'administration de BlueXP "^].

Le tableau suivant indique les actions que chaque rôle de protection contre les ransomwares BlueXP  peut effectuer.

[cols="40,20a,20a"]
|===
| Fonction et action | Administrateur de la protection contre les ransomwares | Visualiseur de protection contre les ransomware 


| Afficher le tableau de bord et tous les onglets  a| 
Oui
 a| 
Oui



| Sur le tableau de bord, mettez à jour l'état des recommandations  a| 
Oui
 a| 
Non



| Essayer gratuitement  a| 
Oui
 a| 
Non



| Lancez la découverte des charges de travail  a| 
Oui
 a| 
Non



| Lancez la redécouverte des charges de travail  a| 
Oui
 a| 
Non



3+| *Sur l'onglet protéger* : 


| Ajoutez, modifiez ou supprimez des plans de protection  a| 
Oui
 a| 
Non



| Protégez les workloads  a| 
Oui
 a| 
Non



| Identifiez l'exposition aux données sensibles  a| 
Oui
 a| 
Non



| Répertoriez les plans de protection et les détails  a| 
Oui
 a| 
Oui



| Répertorier les groupes de protection  a| 
Oui
 a| 
Oui



| Afficher les détails du groupe de protection  a| 
Oui
 a| 
Oui



| Créer, modifier ou supprimer un groupe de protection  a| 
Oui
 a| 
Non



| Téléchargez les données  a| 
Oui
 a| 
Oui



3+| *Sur l'onglet alertes* : 


| Afficher les alertes et les détails des alertes  a| 
Oui
 a| 
Oui



| Modifier l'état de l'incident  a| 
Oui
 a| 
Non



| Marquer l'alerte pour la restauration  a| 
Oui
 a| 
Non



| Afficher les détails de l'incident  a| 
Oui
 a| 
Oui



| Ignorer ou résoudre les incestes  a| 
Oui
 a| 
Non



| Bloquer l'utilisateur  a| 
Oui
 a| 
Non



| Obtenir la liste complète des fichiers affectés  a| 
Oui
 a| 
Non



| Télécharger les données d'alertes  a| 
Oui
 a| 
Oui



3+| *Sur l'onglet récupérer* : 


| Télécharger les fichiers impactés  a| 
Oui
 a| 
Non



| Restaurer la charge de travail  a| 
Oui
 a| 
Non



| Télécharger les données de récupération  a| 
Oui
 a| 
Oui



| Télécharger des rapports  a| 
Oui
 a| 
Oui



3+| *Sur l'onglet Paramètres* : 


| Ajouter ou modifier des destinations de sauvegarde  a| 
Oui
 a| 
Non



| Liste des destinations de sauvegarde  a| 
Oui
 a| 
Oui



| Afficher les cibles SIEM connectées  a| 
Oui
 a| 
Oui



| Ajouter ou modifier des cibles SIEM  a| 
Oui
 a| 
Non



| Connecter les cibles de sécurité des charges de travail  a| 
Oui
 a| 
Non



| Afficher l'état de connexion de sécurité de la charge de travail  a| 
Oui
 a| 
Oui



| Déconnectez les cibles de sécurité de la charge de travail  a| 
Oui
 a| 
Non



| Configurer l'exercice de préparation  a| 
Oui
 a| 
Non



| Commencer l'exercice de préparation  a| 
Oui
 a| 
Non



| Réinitialiser l'exercice de préparation  a| 
Oui
 a| 
Non



| Modifier l'exercice de préparation  a| 
Oui
 a| 
Non



| Passez en revue le statut de l'exercice de préparation  a| 
Oui
 a| 
Oui



| Mettre à jour la configuration de découverte  a| 
Oui
 a| 
Non



| Afficher la configuration de découverte  a| 
Oui
 a| 
Oui



3+| *Sur l'onglet Rapports* : 


| Télécharger des rapports  a| 
Oui
 a| 
Oui

|===