---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Pour configurer la protection contre les ransomwares BlueXP, effectuez quelques étapes. 
---
= Configurez la protection BlueXP contre les ransomware
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: /media/


[role="lead"]
Pour configurer la protection contre les ransomwares BlueXP, effectuez quelques étapes.

Avant de commencer, consultez link:rp-start-prerequisites.html["prérequis"] pour vous assurer que votre environnement est prêt.



== Préparer la destination de sauvegarde

Préparez l'une des destinations de sauvegarde suivantes :

* NetApp StorageGRID
* Amazon Web Services
* Microsoft Azure


Une fois que vous avez configuré les options de la destination de sauvegarde elle-même, vous la configurez ultérieurement en tant que destination de sauvegarde dans le service de protection contre les ransomwares BlueXP.



=== Préparez StorageGRID à devenir une destination de sauvegarde

Si vous souhaitez utiliser StorageGRID comme destination de sauvegarde, reportez-vous à la section https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentation StorageGRID"^] Pour plus d'informations sur StorageGRID.



=== Préparez AWS à devenir une destination de sauvegarde

* Configuration d'un compte dans AWS.
* Configurer https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Autorisations AWS"^] Dans AWS.


Pour en savoir plus sur la gestion de votre stockage AWS dans BlueXP, consultez la section https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Gestion de vos compartiments Amazon S3"^].



=== Préparez Azure à devenir une destination de sauvegarde

* Configuration d'un compte dans Azure.
* Configurer https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Autorisations Azure"^] Dans Azure.


Pour en savoir plus sur la gestion de votre stockage Azure dans BlueXP, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Gérez vos comptes de stockage Azure"^].



== Configurez BlueXP

L'étape suivante consiste à configurer BlueXP et le service de protection contre les ransomwares BlueXP.

Révision https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Exigences standard de BlueXP"^].



=== Créez un connecteur dans BlueXP

Contactez votre ingénieur commercial NetApp pour essayer ou utiliser ce service. Ensuite, lorsque vous utilisez le connecteur BlueXP, il inclut les fonctionnalités appropriées pour le service de protection contre les ransomware.

Pour créer un connecteur dans BlueXP avant d'utiliser le service, reportez-vous à la documentation BlueXP qui décrit https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Comment créer un connecteur BlueXP"^].


NOTE: Si vous disposez de plusieurs connecteurs BlueXP, le service analyse les données entre tous les connecteurs au-delà de celui qui s'affiche actuellement dans l'interface utilisateur BlueXP. Ce service détecte tous les projets et tous les connecteurs associés à cette organisation.
