---
sidebar: sidebar 
permalink: rp-start-disable.html 
keywords: bluexp, ransomware protection, netapp, disable protection 
summary: Si vous ne souhaitez plus utiliser le service de protection contre les ransomwares BlueXP , vous pouvez laisser la licence expirer. 
---
= Désactivez la protection BlueXP  contre les ransomware
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media


[role="lead"]
Si vous ne souhaitez plus utiliser le service de protection contre les ransomwares BlueXP , vous pouvez laisser la licence expirer. Vous pouvez également désactiver les stratégies que vous ne souhaitez plus utiliser.



== Désactivez le service de protection contre les ransomware BlueXP 

Après expiration de l'abonnement ou de la licence, le service désactive automatiquement les fonctionnalités nécessitant un abonnement ou une licence.

Pour plus de détails sur les actions que vous pouvez toujours effectuer après l'expiration de la licence, reportez-vous à la section link:rp-start-licenses.html["Configurez les licences de protection contre les ransomware BlueXP "].



== Désactivez les stratégies de protection

Si vous souhaitez arrêter d'utiliser des règles de protection appliquées aux workloads, vous pouvez les désactiver à l'aide de System Manager, d'appels d'API ou de l'interface de ligne de commande.

Vous pouvez désactiver FPolicy et les règles de sauvegarde dans la protection contre les ransomwares de BlueXP  en appliquant une règle différente qui ne les inclut pas. Pour obtenir des instructions sur la définition des stratégies de protection, reportez-vous link:rp-use-protect.html["Protégez vos workloads contre les attaques par ransomware"]à la section .


TIP: Nous vous recommandons de ne pas désactiver les règles relatives aux snapshots.
