---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question. 
---
= Forum aux questions sur la protection contre les ransomwares BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question.



== L'accès

*Quelle est l'URL de protection contre les ransomware BlueXP ?*
Pour l'URL, dans un navigateur, entrez : https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] Pour accéder à la console BlueXP.

*Avez-vous besoin d'une licence pour utiliser la protection contre les ransomware BlueXP ?*
Aucun fichier de licence NetApp n'est requis. La préversion de la protection contre les ransomware BlueXP elle-même ne nécessite aucune licence spéciale.  Toutes les licences d'aperçu sont des licences d'évaluation.

La version préliminaire de ce service nécessite une licence du service de sauvegarde et de restauration BlueXP.


TIP: Pour la version de prévisualisation, NetApp vous aide à configurer l'évaluation et les licences requises.

*Comment activez-vous la protection contre les ransomware BlueXP ?*
La protection contre les ransomwares BlueXP ne nécessite aucune activation. L'option de protection contre les ransomware est automatiquement activée dans le menu de navigation gauche de BlueXP.

Pour obtenir la version préliminaire, vous devez vous inscrire ou contacter votre ingénieur commercial NetApp pour essayer ce service. Ensuite, lorsque vous utilisez le connecteur BlueXP, il inclut les fonctionnalités appropriées pour le service.

**La protection BlueXP contre les ransomware est-elle disponible en modes standard, restreint et privé ?**
Pour l'instant, la protection contre les ransomwares BlueXP n'est disponible qu'en mode standard. Restez à l'affût de tout.

Pour plus d'informations sur ces modes dans tous les services BlueXP, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modes de déploiement BlueXP"^].

**Comment les autorisations d'accès sont-elles gérées?**
Seuls les administrateurs de comptes ont la possibilité de lancer le service et de découvrir les workloads (car cela implique de s'engager à utiliser une ressource). Les interactions suivantes peuvent être effectuées par n'importe quel rôle.

**Quelle est la meilleure résolution de périphérique?**
La résolution recommandée pour la protection contre les ransomwares BlueXP est de 1920 x 1080 ou supérieure.

**Quel navigateur dois-je utiliser?**
N'importe quel navigateur moderne fonctionnera.



== Interaction avec d'autres services

*La protection contre les ransomware BlueXP est-elle consciente des paramètres de protection créés dans NetApp ONTAP ?*
Oui, la protection contre les ransomware BlueXP découvre les calendriers Snapshot définis dans ONTAP.

*Si vous avez défini une stratégie à l'aide de la protection contre les ransomware BlueXP, devez-vous apporter des modifications futures uniquement dans ce service ?*
Non, vous pouvez modifier les règles à partir de n'importe quel service.



== Charges de travail

**Qu'est-ce qui constitue une charge de travail?**
Une charge de travail inclut tous les volumes utilisés par une seule instance d'application. Par exemple, une instance de base de données Oracle déployée sur ora3.host.com peut avoir vol1 et vol2 pour ses données et ses journaux, respectivement. Ces volumes constituent ensemble la charge de travail de cette instance spécifique de l'instance Oracle DB.

*Comment la protection par ransomware BlueXP hiérarchise-t-elle les données de workload ?*
La priorité des données pour la version d'aperçu dépend des copies Snapshot effectuées et des sauvegardes planifiées.

La priorité de la charge de travail est déterminée par les fréquences Snapshot suivantes :

* *Critique* : copies Snapshot prises moins de 1 par heure (planning de protection extrêmement agressif)
* *Important* : copies snapshot prises moins de 1 par jour mais supérieures à 1 par heure
* *Standard*: Copies snapshot prises plus de 1 par jour


**Nouveau volume ajouté, mais n'apparaît pas encore**
Si vous avez ajouté un volume à votre environnement, lancez de nouveau la découverte et appliquez des règles de protection pour protéger ce nouveau volume.

**Le tableau de bord n'affiche pas toutes mes charges de travail. Qu'est-ce qui pourrait se passer?**
Actuellement, seuls les volumes NFS sont pris en charge. Les volumes iSCSI, les volumes CIFS et les autres configurations non prises en charge sont filtrés et n'apparaissent pas dans le tableau de bord.



== Règles de protection

*Les politiques de ransomware de BlueXP coexistent-elles avec les autres types de politiques de workloads ?*
À ce stade, la sauvegarde et la restauration BlueXP (Cloud Backup) prennent en charge une règle de sauvegarde par volume. Ainsi, la sauvegarde et la restauration BlueXP ainsi que la protection contre les ransomwares BlueXP partagent les politiques de sauvegarde.

Les copies Snapshot ne sont pas limitées et peuvent être ajoutées séparément pour chaque service.
