---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: Commencez à utiliser la protection contre les ransomwares BlueXP en vérifiant la prise en charge de votre environnement, de votre accès réseau, de votre connexion et de votre navigateur web. 
---
= Protection BlueXP contre les ransomware requise
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Commencez à utiliser la protection contre les ransomwares BlueXP en vérifiant le niveau de préparation de votre environnement opérationnel, de votre connexion, de votre accès réseau et de votre navigateur Web.

Pour utiliser la protection contre les ransomwares BlueXP, vous devez disposer des conditions préalables suivantes :

* Un compte dans NetApp StorageGRID ou AWS S3 pour les cibles de sauvegarde et les autorisations d'accès définies
+
Reportez-vous à la https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Liste d'autorisations AWS"^] pour plus d'informations.

* ONTAP 9.11.1 et versions ultérieures
+
** Autorisations ONTAP de l'administrateur du cluster
** Une licence pour la protection anti-ransomware autonome de NetApp, utilisée par la protection anti-ransomware BlueXP, activée sur l'instance ONTAP sur site, selon la version de ONTAP que vous utilisez. Reportez-vous à la section https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Présentation de la protection autonome contre les ransomwares"^].
+

NOTE: Contrairement à la version d'aperçu, la version générale de la protection contre les ransomware BlueXP inclut une licence pour la technologie de protection anti-ransomware autonome de NetApp. Reportez-vous à la section https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Présentation de la protection autonome contre les ransomwares"^] pour plus d'informations.

+
Pour plus d'informations sur les licences, reportez-vous à la section link:concept-ransomware-protection.html["Découvrez la protection contre les ransomwares BlueXP"].



* Dans BlueXP :
+
** Environnement de travail BlueXP avec le stockage sur site NetApp (utilisant les protocoles NAS ou CIFS)
** Un connecteur BlueXP pour chaque cloud privé virtuel (VPC) ou une région sur site doit être configuré dans BlueXP. Reportez-vous à la section https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Documentation BlueXP pour configurer le connecteur"^].
+

NOTE: Si vous disposez de plusieurs connecteurs BlueXP, le service analyse les données entre tous les connecteurs au-delà de celui qui s'affiche actuellement dans l'interface utilisateur BlueXP.

** Un compte BlueXP avec au moins un connecteur actif connecté aux clusters ONTAP sur site. Tous les environnements source et de travail doivent se trouver sur le même compte BlueXP.
** Un compte utilisateur BlueXP avec des privilèges d'administrateur de compte pour la découverte des ressources
** Environnement de travail BlueXP avec le stockage sur site NetApp (utilisant les protocoles NAS ou CIFS)
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Exigences standard de BlueXP"^]





NOTE: Le service de sauvegarde et de restauration BlueXP n'a plus besoin d'être déjà activé dans l'environnement de travail. Le service de protection contre les ransomwares BlueXP permet de configurer une destination de sauvegarde via l'option Paramètres. Voir link:rp-use-settings.html["Configurer les paramètres"].
