= Prise en charge de la charge de travail SAN
:allow-uri-read: 




=== Prise en charge de la charge de travail SAN

Cette version inclut la prise en charge des charges de travail SAN dans la BlueXP ransomware protection. Vous pouvez désormais protéger les charges de travail SAN en plus des charges de travail NFS et CIFS.

Pour plus d'informations, reportez-vous link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Protection BlueXP contre les ransomware requise"]à .



=== Protection améliorée de la charge de travail

Cette version améliore le processus de configuration des charges de travail avec des stratégies de snapshots et de sauvegarde issues d'autres outils NetApp , tels que SnapCenter ou BlueXP backup and recovery. Dans les versions précédentes, la BlueXP ransomware protection détectait les stratégies d'autres outils, vous permettant uniquement de modifier la stratégie de détection. Avec cette version, vous pouvez désormais remplacer les stratégies de snapshots et de sauvegarde par des stratégies de BlueXP ransomware protection ou continuer à utiliser celles d'autres outils.

Pour plus de détails, reportez-vous à link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Protégez les workloads"].



=== Notifications par e-mail

Si la BlueXP ransomware protection détecte une attaque possible, une notification apparaît dans les notifications BlueXP et un e-mail est envoyé à l'adresse e-mail que vous avez configurée.

L'e-mail contient des informations sur la gravité, la charge de travail impactée et un lien vers l'alerte dans l'onglet *Alertes* de BlueXP ransomware protection .

Si vous avez configuré un système de gestion de la sécurité et des événements (SIEM) dans la BlueXP ransomware protection, le service envoie les détails de l'alerte à votre système SIEM.

Pour plus de détails, reportez-vous à link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Gérer les alertes de ransomware détectées"].
