= Signalement d'environnements de travail non pris en charge dans la protection contre les ransomwares BlueXP 
:allow-uri-read: 




=== Signalement d'environnements de travail non pris en charge dans la protection contre les ransomwares BlueXP 

Au cours du workflow de découverte, la protection contre les ransomwares de BlueXP  fournit des informations supplémentaires lorsque vous survolez les workloads pris en charge ou non pris en charge. Ainsi, vous comprendrez pourquoi certains de vos workloads ne sont pas découverts par le service de protection BlueXP  contre les ransomware.

Il existe de nombreuses raisons pour lesquelles le service ne prend pas en charge un environnement de travail. Par exemple, la version ONTAP de votre environnement de travail peut être inférieure à la version requise. Lorsque vous placez le pointeur de la souris sur un environnement de travail non pris en charge, une info-bulle affiche la raison.

Vous pouvez afficher les environnements de travail non pris en charge lors de la découverte initiale, où vous pouvez également télécharger les résultats. Vous pouvez également afficher les résultats de la découverte à partir de l'option *Workload Discovery* de la page Paramètres.

Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Découvrez les workloads dans la solution de protection BlueXP contre les ransomwares"] .
